# Makefile - GraphicsExamples

.PHONY: all
all: \
	Constraints \
	Events \
	HelloHaptics \
	HelloSphere \
	HelloSphereDual \
	PointManipulation \
	ShapeManipulation \
	SimpleDeformableSurface \
	SimpleRigidBodyDynamics \
	HL_DOP_Demo \
	SimplePinchDemo

.PHONY: Constraints
Constraints:
	$(MAKE) -C Constraints

.PHONY: Events
Events:
	$(MAKE) -C Events

.PHONY: HelloHaptics
HelloHaptics:
	$(MAKE) -C HelloHaptics

.PHONY: HelloSphere
HelloSphere:
	$(MAKE) -C HelloSphere

.PHONY: HelloSphereDual
HelloSphereDual:
	$(MAKE) -C HelloSphereDual

.PHONY: PointManipulation
PointManipulation:
	$(MAKE) -C PointManipulation

.PHONY: ShapeManipulation
ShapeManipulation:
	$(MAKE) -C ShapeManipulation

.PHONY: SimpleDeformableSurface
SimpleDeformableSurface:
	$(MAKE) -C SimpleDeformableSurface

.PHONY: SimpleRigidBodyDynamics
SimpleRigidBodyDynamics:
	$(MAKE) -C SimpleRigidBodyDynamics

.PHONY: HL_DOP_Demo
HL_DOP_Demo:
	$(MAKE) -C HL_DOP_Demo

.PHONY: SimplePinchDemo
SimplePinchDemo:
	$(MAKE) -C SimplePinchDemo


.PHONY: clean
clean:
	$(MAKE) -C Constraints clean
	$(MAKE) -C Events clean
	$(MAKE) -C HelloHaptics clean
	$(MAKE) -C HelloSphere clean
	$(MAKE) -C HelloSphereDual clean
	$(MAKE) -C PointManipulation clean
	$(MAKE) -C ShapeManipulation clean
	$(MAKE) -C SimpleDeformableSurface clean
	$(MAKE) -C SimpleRigidBodyDynamics clean
	$(MAKE) -C HL_DOP_Demo clean
	$(MAKE) -C SimplePinchDemo clean
