# Makefile - QuickHapticsExamples

.PHONY: all
all: 
	$(MAKE) -C ComplexScene/ComplexSceneGLUT 
	$(MAKE) -C EarthSpin/EarthSpinGLUT 
	$(MAKE) -C pickApples/pickApplesGLUT 
	$(MAKE) -C ShapeDepthFeedback/ShapeDepthFeedbackGLUT 
	$(MAKE) -C SimpleSphere/SimpleSphereGLUT 
	$(MAKE) -C SkullCoulombForce/SkullCoulombForceGLUT 
	$(MAKE) -C SpongyCow/SpongyCowGLUT 
	$(MAKE) -C TeethCavityPick/TeethCavityPickGLUT 

.PHONY: ComplexScene
ComplexScene:
	$(MAKE) -C ComplexScene/ComplexSceneGLUT 

.PHONY: EarthSpin
EarthSpin:
	$(MAKE) -C EarthSpin/EarthSpinGLUT

.PHONY: pickApples
pickApples:
	$(MAKE) -C pickApples/pickApplesGLUT

.PHONY: ShapeDepthFeedback
ShapeDepthFeedback:
	$(MAKE) -C ShapeDepthFeedback/ShapeDepthFeedbackGLUT

.PHONY: SimpleSphere
SimpleSphere:
	$(MAKE) -C SimpleSphere/SimpleSphereGLUT

.PHONY: SkullCoulombForce
SkullCoulombForce:
	$(MAKE) -C SkullCoulombForce/SkullCoulombForceGLUT

.PHONY: SpongyCow
SpongyCow:
	$(MAKE) -C SpongyCow/SpongyCowGLUT

.PHONY: TeethCavityPick
TeethCavityPick:
	$(MAKE) -C TeethCavityPick/TeethCavityPickGLUT

.PHONY: clean
clean:
	$(MAKE) -C ComplexScene/ComplexSceneGLUT clean
	$(MAKE) -C EarthSpin/EarthSpinGLUT clean
	$(MAKE) -C pickApples/pickApplesGLUT clean
	$(MAKE) -C ShapeDepthFeedback/ShapeDepthFeedbackGLUT clean
	$(MAKE) -C SimpleSphere/SimpleSphereGLUT clean
	$(MAKE) -C SkullCoulombForce/SkullCoulombForceGLUT clean
	$(MAKE) -C SpongyCow/SpongyCowGLUT clean
	$(MAKE) -C TeethCavityPick/TeethCavityPickGLUT clean
