# Makefile - ConsoleExamples

.PHONY: all
all: \
	AnchoredSpringForce \
	Calibration \
	ErrorHandling \
	FrictionlessPlane \
	FrictionlessSphere \
	HelloHapticDevice \
	PreventWarmMotors \
	QueryDevice \
	ServoLoopDutyCycle \
	ServoLoopRate \
	CommandMotorDAC \
	CommandJointTorque \
	Vibration

.PHONY: AnchoredSpringForce
AnchoredSpringForce:
	$(MAKE) -C AnchoredSpringForce

.PHONY: Calibration
Calibration:
	$(MAKE) -C Calibration

.PHONY: ErrorHandling
ErrorHandling:
	$(MAKE) -C ErrorHandling

.PHONY: FrictionlessPlane
FrictionlessPlane:
	$(MAKE) -C FrictionlessPlane

.PHONY: FrictionlessSphere
FrictionlessSphere:
	$(MAKE) -C FrictionlessSphere

.PHONY: HelloHapticDevice
HelloHapticDevice:
	$(MAKE) -C HelloHapticDevice

.PHONY: PreventWarmMotors
PreventWarmMotors:
	$(MAKE) -C PreventWarmMotors

.PHONY: QueryDevice
QueryDevice:
	$(MAKE) -C QueryDevice

.PHONY: ServoLoopDutyCycle
ServoLoopDutyCycle:
	$(MAKE) -C ServoLoopDutyCycle

.PHONY: ServoLoopRate
ServoLoopRate:
	$(MAKE) -C ServoLoopRate

.PHONY: Vibration
Vibration:
	$(MAKE) -C Vibration

.PHONY: CommandMotorDAC
Vibration:
	$(MAKE) -C CommandMotorDAC

.PHONY: CommandJointTorque
Vibration:
	$(MAKE) -C CommandJointTorque

.PHONY: clean
clean:
	$(MAKE) -C AnchoredSpringForce clean
	$(MAKE) -C Calibration clean
	$(MAKE) -C QueryDevice clean
	$(MAKE) -C ErrorHandling clean
	$(MAKE) -C FrictionlessPlane clean
	$(MAKE) -C FrictionlessSphere clean
	$(MAKE) -C HelloHapticDevice clean
	$(MAKE) -C PreventWarmMotors clean
	$(MAKE) -C ServoLoopDutyCycle clean
	$(MAKE) -C ServoLoopRate clean
	$(MAKE) -C Vibration clean
	$(MAKE) -C CommandMotorDAC clean
	$(MAKE) -C CommandJointTorque clean


