# Makefile - GraphicsExamples

.PHONY: all
all: \
	CoulombField \
	CoulombForceDual \
	ParticleWaltz \
	PointManipulation \
	PointSnapping \
	SimpleHapticScene \
	SlidingContact

.PHONY: CoulombField
CoulombField:
	$(MAKE) -C CoulombField

.PHONY: CoulombForceDual
CoulombForceDual:
	$(MAKE) -C CoulombForceDual

.PHONY: ParticleWaltz
ParticleWaltz:
	$(MAKE) -C ParticleWaltz

.PHONY: PointManipulation
PointManipulation:
	$(MAKE) -C PointManipulation

.PHONY: PointSnapping
PointSnapping:
	$(MAKE) -C PointSnapping

.PHONY: SimpleHapticScene
SimpleHapticScene:
	$(MAKE) -C SimpleHapticScene

.PHONY: SlidingContact
SlidingContact:
	$(MAKE) -C SlidingContact

.PHONY: clean
clean:
	$(MAKE) -C CoulombField clean
	$(MAKE) -C CoulombForceDual clean
	$(MAKE) -C ParticleWaltz clean
	$(MAKE) -C PointManipulation clean
	$(MAKE) -C PointSnapping clean
	$(MAKE) -C SimpleHapticScene clean
	$(MAKE) -C SlidingContact clean


